Write a Python program to convert an array to an ordinary list with the same items.

We can use the np.tolist() function.

In [3]:
import numpy as np
array1 = np.array([1, 2, 3, "suzan"])

print(array1)

list1 = array1.tolist()

print(list1)

['1' '2' '3' 'suzan']
['1', '2', '3', 'suzan']


Write a NumPy program to compute the sum of the diagonal elements of a given array.

Hint: There are two possible methods to solve this problem: 

Manually (without direct function). 
Using the trace function

In [7]:
import numpy as np

numPy_array = np.array([[5, 5, 12],
                        [6, 4, 9],
                       [2,7,10]])
  

print(numPy_array)

trace1 = np.trace(numPy_array) 

print(trace1)

[[ 5  5 12]
 [ 6  4  9]
 [ 2  7 10]]
19


Given an array of your choice, get all the values higher than X:

If a = [[1,2],[3,5]] and x = 2 :  then 3 and 5 are higher than 2. 

In [9]:
import numpy as np
a = np.array([[1, 2], [3, 5]])
print(a[a>2])


[3 5]


Given two arrays, A & B have the same shape. 

The task is to apply addition by hand: C is the new array. 

In [11]:
A = np.array([(6, 7),
              (4, 9),
              (3, 8)])
B = np.array([(1, 2),
              (3, 4),
              (5, 6)])
C= A+B
print(C)

[[ 7  9]
 [ 7 13]
 [ 8 14]]


Write a NumPy program to subtract the mean of each row of a given matrix.

Hint: use the mean function

In [16]:
import numpy as np
a = np.random.randint[(10, 23)]
print(a)
b = a - a.mean(axis=1)
print(b)

TypeError: 'builtin_function_or_method' object is not subscriptable